# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ur5_manipulator_controller
    - joint_trajectory_controller

  ur5_manipulator_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      []
    action_ns: follow_joint_trajectory
    default: true